In [1]:
a = [1,2,3]
b = [5,6,7]
print(a+b)

[1, 2, 3, 5, 6, 7]


In [7]:
import numpy as np

a = [1,2,3]
np_a = np.array(a)
b = [5,6,7]
np_b = np.array(b)

In [5]:
type(a)

list

In [6]:
type(np_a)

numpy.ndarray

In [9]:
np_a+np_b

array([ 6,  8, 10])

In [11]:
A = [[1,2,3],[4,5,6]]
npa = np.array(A)

In [12]:
npa

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# vektor
a = [1,2,3]
np_a = np.array(a)
b = [5,6,7]
np_b = np.array(b)

In [14]:
print(np_a+np_b)
print(np_a-np_b)

[ 6  8 10]
[-4 -4 -4]


In [15]:
# dot product
dot_product = np_a @ np_b
print(dot_product)

38


In [16]:
# cross product
cross_product = np.cross(np_a, np_b)
print(cross_product)

[-4  8 -4]


In [17]:
from numpy.linalg import norm

In [19]:
norm(a)

3.7416573867739413

In [21]:
np.sqrt(14)

3.7416573867739413

In [23]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
I = np.eye(3)

In [28]:
A @ I

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [31]:
from numpy.linalg import inv

B = np.array([[1,3],[2,5]])
inv_B = inv(B)
inv_B

array([[-5.,  3.],
       [ 2., -1.]])

In [32]:
B @ inv_B

array([[1., 0.],
       [0., 1.]])

In [33]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [34]:
a % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [37]:
# masking a[kondisi]
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [38]:
A.sum()

45

In [41]:
A.sum(axis=0) #perkolom

array([12, 15, 18])

In [42]:
A.sum(axis=1) #perbaris

array([ 6, 15, 24])

In [48]:
# dosen dengan 50 mhs
# tugas, prak, uts, uas
# NA = 10% tugas + 15% prak + 35% uts + 40% uas
# nilai_tugas = np.random.normal(rata", standar deviasi, size=(50,))
nilai_tugas = np.random.normal(80, 7, size=(50,))
nilai_tugas

array([91.46022269, 71.8801173 , 76.74056014, 86.53924767, 73.48617275,
       77.73463915, 74.22397171, 69.25325788, 89.62480398, 79.97989682,
       80.11293619, 73.75220855, 91.45161126, 76.65002843, 78.24656766,
       87.23279896, 70.50115847, 79.45922532, 81.449279  , 68.24326285,
       73.68694116, 83.07602457, 69.19769311, 86.99935885, 77.89824052,
       71.60011181, 77.71805122, 75.23824966, 87.75172039, 72.78791924,
       78.28602094, 63.95304623, 72.19437292, 80.78265283, 70.08660838,
       84.4267315 , 67.9976985 , 78.11134081, 76.67572279, 70.5627841 ,
       87.81980454, 74.07593349, 76.98376579, 69.16400768, 83.8327376 ,
       74.97402906, 74.09822491, 88.4551154 , 80.77141593, 78.86854228])

In [49]:
nilai_prak = np.random.normal(90, 2, size=(50,))
nilai_prak

array([86.06430129, 86.50388695, 92.23759191, 92.03591847, 89.60336869,
       92.15284649, 88.87043768, 86.77795546, 91.85798715, 89.50818363,
       91.46183496, 92.74788437, 91.77071894, 92.72765228, 91.47960632,
       86.80755896, 91.3147784 , 88.91675111, 95.00325055, 89.62612705,
       89.2108787 , 88.11391189, 87.72393339, 90.95605357, 87.77988376,
       90.5252849 , 94.1717886 , 88.76560365, 85.81852553, 87.09263733,
       93.25425268, 90.8714552 , 89.4465614 , 89.93508943, 91.62996042,
       88.51969683, 88.68384289, 90.96819404, 89.88038696, 89.08246697,
       90.33966522, 89.66822078, 89.32174349, 90.65118666, 90.82291335,
       85.10538267, 90.93710603, 90.6521171 , 87.51209647, 87.79147941])

In [50]:
nilai_uts = np.random.normal(63, 15, size=(50,))
nilai_uts

array([58.41243394, 74.00808588, 71.31411833, 76.95911329, 48.86982785,
       84.75222394, 35.69267925, 51.48139816, 52.31167451, 28.47126611,
       38.92524205, 71.68947864, 41.72734609, 57.90620047, 77.41245534,
       56.59581897, 45.79930101, 80.57632424, 57.21096483, 46.4510103 ,
       42.15293281, 43.60044013, 56.21052254, 43.23293745, 44.15657019,
       54.18947688, 63.69853802, 57.03474663, 48.69049556, 62.15595761,
       49.24322518, 68.69764322, 69.70815224, 81.78159476, 52.97770102,
       69.87325184, 50.44372394, 48.7784178 , 48.27500181, 71.446933  ,
       38.37349318, 74.75940559, 70.12259359, 45.43771921, 57.98582133,
       71.91729153, 53.13727386, 72.4342222 , 46.91107456, 89.11146982])

In [51]:
nilai_uas = np.random.normal(75, 10, size=(50,))
nilai_uas

array([70.21196063, 78.43346436, 83.49248988, 82.49771699, 80.70388804,
       77.54043235, 70.94049067, 70.45940189, 82.50698891, 67.43840099,
       76.95815608, 80.70741798, 73.99175898, 72.72738785, 65.79271683,
       84.60759734, 70.38409473, 92.3671543 , 83.71753938, 55.41517404,
       69.10313695, 84.09364707, 55.80354151, 79.43976294, 62.75407776,
       63.78667216, 98.13802709, 68.68824863, 70.17366271, 75.89814575,
       71.95838847, 74.63851963, 88.88360468, 60.77201455, 83.41556998,
       78.80732177, 67.30094581, 69.04883512, 66.03825537, 74.60977647,
       77.19555634, 83.02160614, 68.31668997, 63.36736411, 67.03184495,
       82.69494554, 74.97866017, 92.96348656, 80.06596641, 79.38436635])

In [52]:
nilai_akhir = 0.1 * nilai_tugas + 0.15 * nilai_prak + 0.35 * nilai_uts + 0.4 * nilai_uas
nilai_akhir

array([70.5848036 , 77.43981058, 79.86663217, 82.39408898, 70.17511754,
       82.27584221, 61.62159683, 66.14426922, 74.05306011, 58.36452076,
       66.13766601, 78.66168823, 67.11204369, 70.93227599, 74.95804382,
       75.39598932, 64.93072585, 86.4320104 , 75.90626893, 58.69216857,
       63.14510719, 70.42230212, 62.07345881, 69.2507772 , 61.51323729,
       65.21978969, 83.44727255, 68.27612629, 66.7590894 , 72.45653099,
       67.8352242 , 73.92560588, 80.58771666, 74.50089268, 72.66157825,
       77.69919453, 64.67802799, 66.14834346, 64.4611831 , 75.26898559,
       66.64187539, 80.23226088, 72.96622185, 61.76422613, 69.1144862 ,
       78.51224056, 69.63989832, 84.9807015 , 69.64921872, 83.99833712])

In [53]:
nilai_akhir[nilai_akhir > 75]

array([77.43981058, 79.86663217, 82.39408898, 82.27584221, 78.66168823,
       75.39598932, 86.4320104 , 75.90626893, 83.44727255, 80.58771666,
       77.69919453, 75.26898559, 80.23226088, 78.51224056, 84.9807015 ,
       83.99833712])

In [54]:
absen = np.arange(1,51)
absen

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [56]:
absen[nilai_akhir > 80]

array([ 4,  6, 18, 27, 33, 42, 48, 50])

In [57]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [58]:
a[(a % 2 == 1) & (a > 5)]

array([7, 9])

In [61]:
from random import randint

randint(0, 9)

7